/*
 * Copyright 2011 Jens Dietrich Licensed under the GNU AFFERO GENERAL PUBLIC LICENSE, Version 3
 * (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * http://www.gnu.org/licenses/agpl.html Unless required by applicable law
 * or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */


package nz.ac.massey.cs.guery.ccc;

import edu.uci.ics.jung.graph.DirectedGraph;
import nz.ac.massey.cs.gql4jung.TypeNode;
import nz.ac.massey.cs.gql4jung.TypeRef;
import nz.ac.massey.cs.gql4jung.io.JarReader;
import nz.ac.massey.cs.guery.impl.ccc.ChainDecompositionReachabilityAnalyser2;
import nz.ac.massey.cs.guery.impl.ccc.Direction;
import nz.ac.massey.cs.guery.impl.ccc.ReachabilityAnalyser;
import nz.ac.massey.cs.guery.util.NullFilter;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import java.io.File;
import java.net.URL;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

/**
 * Tests for the chain compression based reachability analyser.
 * Test data are generated by TestGenerator.
 * Can be run as test case, or as an executable (main) - the executable prints performance data to the console.
 *
 * @author jens dietrich
 */


@RunWith(Parameterized.class)
public class TestLog4JUsingChainCompressionCache extends AbstractChainCompressionCacheTest {

    static DirectedGraph<TypeNode, TypeRef> g = null;
    static ReachabilityAnalyser RA = null;
    private static Map<String, TypeNode> verticesByFullname = null;


    @BeforeClass
    public static void loadAndIndexGraph() throws Exception {
        final String src = "testdata/log4j-1.2.15.jar";
        URL in = Thread.currentThread().getContextClassLoader().getResource(src);
        File file = new File(in.toURI());
        JarReader reader = new JarReader(file);
        g = reader.readGraph();

        System.out.println("Vertices in " + src + ": " + g.getVertexCount());
        System.out.println("Edges in " + src + ": " + g.getEdgeCount());

        long before = System.currentTimeMillis();

        RA = new ChainDecompositionReachabilityAnalyser2(Direction.BOTH);
        RA.setGraph(new nz.ac.massey.cs.guery.adapters.jung.JungAdapter(g), NullFilter.DEFAULT);

        long after = System.currentTimeMillis();

        System.out.println("Reachability analysis took " + (after - before) + "ms");

        save(g, "data/log4j-1.2.15.dot");

        verticesByFullname = new HashMap<String, TypeNode>();
        for (TypeNode v : g.getVertices()) {
            verticesByFullname.put(v.getFullname(), v);
        }

    }


    public TestLog4JUsingChainCompressionCache(String v1, String v2, boolean reachable) {
        super();
        this.source = verticesByFullname.get(v1);
        this.target = verticesByFullname.get(v2);
        this.reachable = reachable;
    }


    public ReachabilityAnalyser getRA() {
        return RA;
    }

    public DirectedGraph<TypeNode, TypeRef> getGraph() {
        return g;
    }

//	public static void profile(Class clazz,String method,Collection<Object[]> testData) throws Exception {
//		Method m = AbstractTest.class.getMethod(method,new Class[]{});
//		Object[] noparam = new Object[]{};
//		long before = System.currentTimeMillis();
//		for (Object[] param:testData) {
//			TestLog4J test = new TestLog4J((String)param[0],(String)param[1],(Boolean)param[2]);
//			for (int i=0;i<1000;i++) m.invoke(test, noparam);
//		}
//		long after = System.currentTimeMillis();
//		
//		System.out.println("Testing method " + method + " took " + (after-before) + "ms");
//		
//	}

    public static void main(String[] arg) throws Exception {
        TestLog4JUsingChainCompressionCache.loadAndIndexGraph();
        profile(TestLog4JUsingChainCompressionCache.class, "testGetReachableVerticesOUT", getTestData());
        profile(TestLog4JUsingChainCompressionCache.class, "testGetReachableVerticesIN", getTestData());
        profile(TestLog4JUsingChainCompressionCache.class, "testIsReachableOUT", getTestData());
        profile(TestLog4JUsingChainCompressionCache.class, "testIsReachableIN", getTestData());
        profile(TestLog4JUsingChainCompressionCache.class, "testUsingJungDijkstraOnline", getTestData());
    }


    @Parameters
    public static Collection<Object[]> getTestData() {
        return Arrays.asList(new Object[][]{
                // positive test case (reachable)
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$13", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$LogBrokerMonitorWindowAdaptor", true}, // [e-3889:[55:org.apache.log4j.lf5.viewer.LogBrokerMonitor$13 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4349:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 75:org.apache.log4j.lf5.viewer.LogBrokerMonitor$LogBrokerMonitorWindowAdaptor]]
                {"org.apache.log4j.lf5.LF5Appender", "org.apache.log4j.lf5.viewer.FilteredLogTableModel", true}, // [e-8633:[101:org.apache.log4j.lf5.LF5Appender -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4369:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 81:org.apache.log4j.lf5.viewer.FilteredLogTableModel]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$21", "org.apache.log4j.lf5.viewer.LF5SwingUtils$1", true}, // [e-4005:[63:org.apache.log4j.lf5.viewer.LogBrokerMonitor$21 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5542:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 83:org.apache.log4j.lf5.viewer.LF5SwingUtils], e-7199:[83:org.apache.log4j.lf5.viewer.LF5SwingUtils -> 82:org.apache.log4j.lf5.viewer.LF5SwingUtils$1]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$4", "org.apache.log4j.lf5.Log4JLogRecord", true}, // [e-3693:[46:org.apache.log4j.lf5.viewer.LogBrokerMonitor$4 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5303:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 97:org.apache.log4j.lf5.util.LogFileParser], e-8196:[97:org.apache.log4j.lf5.util.LogFileParser -> 104:org.apache.log4j.lf5.Log4JLogRecord]]
                {"org.apache.log4j.xml.Log4jEntityResolver", "org.apache.log4j.helpers.FileWatchdog", true}, // [e-1916:[11:org.apache.log4j.xml.Log4jEntityResolver -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23283:[238:org.apache.log4j.PropertyConfigurator -> 140:org.apache.log4j.helpers.FileWatchdog]]
                {"org.apache.log4j.lf5.viewer.LogFactor5InputDialog$3", "org.apache.log4j.lf5.viewer.LogFactor5Dialog", true}, // [e-3511:[41:org.apache.log4j.lf5.viewer.LogFactor5InputDialog$3 -> 42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog], e-3527:[42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog -> 13:org.apache.log4j.lf5.viewer.LogFactor5Dialog]]
                {"org.apache.log4j.BasicConfigurator", "org.apache.log4j.spi.NOPLogger", true}, // [e-25525:[250:org.apache.log4j.BasicConfigurator -> 240:org.apache.log4j.LogManager], e-24032:[240:org.apache.log4j.LogManager -> 125:org.apache.log4j.spi.NOPLoggerRepository], e-9738:[125:org.apache.log4j.spi.NOPLoggerRepository -> 124:org.apache.log4j.spi.NOPLogger]]
                {"org.apache.log4j.helpers.SyslogQuietWriter", "org.apache.log4j.Appender", true}, // [e-12258:[153:org.apache.log4j.helpers.SyslogQuietWriter -> 117:org.apache.log4j.spi.ErrorHandler], e-9600:[117:org.apache.log4j.spi.ErrorHandler -> 163:org.apache.log4j.Appender]]
                {"org.apache.log4j.jmx.AbstractDynamicMBean", "org.apache.log4j.LogManager", true}, // [e-19089:[213:org.apache.log4j.jmx.AbstractDynamicMBean -> 164:org.apache.log4j.Logger], e-13321:[164:org.apache.log4j.Logger -> 240:org.apache.log4j.LogManager]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$6", "org.apache.log4j.lf5.viewer.configure.MRUFileManager", true}, // [e-3747:[48:org.apache.log4j.lf5.viewer.LogBrokerMonitor$6 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4285:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 80:org.apache.log4j.lf5.viewer.configure.MRUFileManager]]
                {"org.apache.log4j.jmx.LoggerDynamicMBean", "org.apache.log4j.helpers.ThreadLocalMap", true}, // [e-20240:[217:org.apache.log4j.jmx.LoggerDynamicMBean -> 163:org.apache.log4j.Appender], e-13293:[163:org.apache.log4j.Appender -> 108:org.apache.log4j.spi.LoggingEvent], e-9026:[108:org.apache.log4j.spi.LoggingEvent -> 236:org.apache.log4j.MDC], e-23081:[236:org.apache.log4j.MDC -> 152:org.apache.log4j.helpers.ThreadLocalMap]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$30", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$12", true}, // [e-4180:[72:org.apache.log4j.lf5.viewer.LogBrokerMonitor$30 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4810:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 54:org.apache.log4j.lf5.viewer.LogBrokerMonitor$12]]
                {"org.apache.log4j.Layout", "org.apache.log4j.CategoryKey", true}, // [e-13404:[165:org.apache.log4j.Layout -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-10034:[129:org.apache.log4j.Category -> 220:org.apache.log4j.Hierarchy], e-21341:[220:org.apache.log4j.Hierarchy -> 251:org.apache.log4j.CategoryKey]]
                {"org.apache.log4j.varia.NullAppender", "org.apache.log4j.ProvisionNode", true}, // [e-16044:[196:org.apache.log4j.varia.NullAppender -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-10034:[129:org.apache.log4j.Category -> 220:org.apache.log4j.Hierarchy], e-21433:[220:org.apache.log4j.Hierarchy -> 227:org.apache.log4j.ProvisionNode]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$1", "org.apache.log4j.lf5.viewer.LogFactor5InputDialog$1", true}, // [e-3613:[43:org.apache.log4j.lf5.viewer.LogBrokerMonitor$1 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5463:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog], e-3563:[42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog -> 39:org.apache.log4j.lf5.viewer.LogFactor5InputDialog$1]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryPath", true}, // [e-5353:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 18:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel], e-2156:[18:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel -> 20:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryPath]]
                {"org.apache.log4j.helpers.SyslogWriter", "org.apache.log4j.Hierarchy", true}, // [e-11020:[136:org.apache.log4j.helpers.SyslogWriter -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23258:[238:org.apache.log4j.PropertyConfigurator -> 240:org.apache.log4j.LogManager], e-24077:[240:org.apache.log4j.LogManager -> 220:org.apache.log4j.Hierarchy]]
                {"org.apache.log4j.LogManager", "org.apache.log4j.spi.NOPLoggerRepository", true}, // [e-24032:[240:org.apache.log4j.LogManager -> 125:org.apache.log4j.spi.NOPLoggerRepository]]
                {"org.apache.log4j.net.SimpleSocketServer", "org.apache.log4j.DefaultCategoryFactory", true}, // [e-16996:[202:org.apache.log4j.net.SimpleSocketServer -> 238:org.apache.log4j.PropertyConfigurator], e-23243:[238:org.apache.log4j.PropertyConfigurator -> 248:org.apache.log4j.DefaultCategoryFactory]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$25", "org.apache.log4j.lf5.viewer.LogFactor5InputDialog$1", true}, // [e-4050:[67:org.apache.log4j.lf5.viewer.LogBrokerMonitor$25 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5463:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog], e-3563:[42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog -> 39:org.apache.log4j.lf5.viewer.LogFactor5InputDialog$1]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$5", "org.apache.log4j.lf5.viewer.LogFactor5InputDialog$3", true}, // [e-3736:[47:org.apache.log4j.lf5.viewer.LogBrokerMonitor$5 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5463:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog], e-3575:[42:org.apache.log4j.lf5.viewer.LogFactor5InputDialog -> 41:org.apache.log4j.lf5.viewer.LogFactor5InputDialog$3]]
                {"org.apache.log4j.lf5.util.LogFileParser$1", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryElement", true}, // [e-8151:[96:org.apache.log4j.lf5.util.LogFileParser$1 -> 97:org.apache.log4j.lf5.util.LogFileParser], e-8173:[97:org.apache.log4j.lf5.util.LogFileParser -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5353:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 18:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel], e-2163:[18:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel -> 21:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryElement]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$19", "org.apache.log4j.lf5.viewer.LogTableRowRenderer", true}, // [e-3982:[61:org.apache.log4j.lf5.viewer.LogBrokerMonitor$19 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4288:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 78:org.apache.log4j.lf5.viewer.LogTable], e-5954:[78:org.apache.log4j.lf5.viewer.LogTable -> 87:org.apache.log4j.lf5.viewer.LogTableRowRenderer]]
                {"org.apache.log4j.helpers.DateLayout", "org.apache.log4j.spi.ThrowableInformation", true}, // [e-11126:[137:org.apache.log4j.helpers.DateLayout -> 108:org.apache.log4j.spi.LoggingEvent], e-8888:[108:org.apache.log4j.spi.LoggingEvent -> 110:org.apache.log4j.spi.ThrowableInformation]]
                {"org.apache.log4j.spi.LoggerRepository", "org.apache.log4j.spi.LoggingEvent", true}, // [e-9560:[112:org.apache.log4j.spi.LoggerRepository -> 163:org.apache.log4j.Appender], e-13293:[163:org.apache.log4j.Appender -> 108:org.apache.log4j.spi.LoggingEvent]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$29", "org.apache.log4j.lf5.viewer.configure.ConfigurationManager", true}, // [e-4153:[71:org.apache.log4j.lf5.viewer.LogBrokerMonitor$29 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4271:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 79:org.apache.log4j.lf5.viewer.configure.ConfigurationManager]]
                {"org.apache.log4j.PropertyConfigurator", "org.apache.log4j.Appender", true}, // [e-23572:[238:org.apache.log4j.PropertyConfigurator -> 163:org.apache.log4j.Appender]]
                {"org.apache.log4j.spi.NOPLoggerRepository", "org.apache.log4j.spi.RendererSupport", true}, // [e-9724:[125:org.apache.log4j.spi.NOPLoggerRepository -> 129:org.apache.log4j.Category], e-10034:[129:org.apache.log4j.Category -> 220:org.apache.log4j.Hierarchy], e-21262:[220:org.apache.log4j.Hierarchy -> 120:org.apache.log4j.spi.RendererSupport]]
                {"org.apache.log4j.chainsaw.ControlPanel", "org.apache.log4j.spi.Filter", true}, // [e-15037:[183:org.apache.log4j.chainsaw.ControlPanel -> 169:org.apache.log4j.chainsaw.MyTableModel], e-13921:[169:org.apache.log4j.chainsaw.MyTableModel -> 129:org.apache.log4j.Category], e-9859:[129:org.apache.log4j.Category -> 163:org.apache.log4j.Appender], e-13292:[163:org.apache.log4j.Appender -> 115:org.apache.log4j.spi.Filter]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$10", "org.apache.log4j.lf5.util.DateFormatManager", true}, // [e-3830:[52:org.apache.log4j.lf5.viewer.LogBrokerMonitor$10 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5064:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 94:org.apache.log4j.lf5.util.DateFormatManager]]
                {"org.apache.log4j.helpers.OptionConverter", "org.apache.log4j.spi.RootLogger", true}, // [e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23258:[238:org.apache.log4j.PropertyConfigurator -> 240:org.apache.log4j.LogManager], e-24075:[240:org.apache.log4j.LogManager -> 119:org.apache.log4j.spi.RootLogger]]
                {"org.apache.log4j.varia.LevelRangeFilter", "org.apache.log4j.config.PropertySetterException", true}, // [e-15880:[191:org.apache.log4j.varia.LevelRangeFilter -> 108:org.apache.log4j.spi.LoggingEvent], e-9096:[108:org.apache.log4j.spi.LoggingEvent -> 221:org.apache.log4j.or.RendererMap], e-21663:[221:org.apache.log4j.or.RendererMap -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23325:[238:org.apache.log4j.PropertyConfigurator -> 230:org.apache.log4j.config.PropertySetter], e-22371:[230:org.apache.log4j.config.PropertySetter -> 229:org.apache.log4j.config.PropertySetterException]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$14", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$30", true}, // [e-3907:[56:org.apache.log4j.lf5.viewer.LogBrokerMonitor$14 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4940:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 72:org.apache.log4j.lf5.viewer.LogBrokerMonitor$30]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$32", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$8", true}, // [e-4236:[74:org.apache.log4j.lf5.viewer.LogBrokerMonitor$32 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4450:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 50:org.apache.log4j.lf5.viewer.LogBrokerMonitor$8]]
                {"org.apache.log4j.net.SMTPAppender", "org.apache.log4j.spi.NOPLoggerRepository", true}, // [e-17813:[206:org.apache.log4j.net.SMTPAppender -> 9:org.apache.log4j.xml.DOMConfigurator], e-576:[9:org.apache.log4j.xml.DOMConfigurator -> 240:org.apache.log4j.LogManager], e-24032:[240:org.apache.log4j.LogManager -> 125:org.apache.log4j.spi.NOPLoggerRepository]]
                {"org.apache.log4j.lf5.viewer.configure.ConfigurationManager", "org.apache.log4j.lf5.viewer.LogFactor5LoadingDialog", true}, // [e-6054:[79:org.apache.log4j.lf5.viewer.configure.ConfigurationManager -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5303:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 97:org.apache.log4j.lf5.util.LogFileParser], e-8172:[97:org.apache.log4j.lf5.util.LogFileParser -> 88:org.apache.log4j.lf5.viewer.LogFactor5LoadingDialog]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$LogBrokerMonitorWindowAdaptor", "org.apache.log4j.lf5.viewer.LogTable", true}, // [e-4253:[75:org.apache.log4j.lf5.viewer.LogBrokerMonitor$LogBrokerMonitorWindowAdaptor -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4288:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 78:org.apache.log4j.lf5.viewer.LogTable]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$31", "org.apache.log4j.lf5.viewer.FilteredLogTableModel", true}, // [e-4209:[73:org.apache.log4j.lf5.viewer.LogBrokerMonitor$31 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4369:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 81:org.apache.log4j.lf5.viewer.FilteredLogTableModel]]
                {"org.apache.log4j.DailyRollingFileAppender", "org.apache.log4j.helpers.FileWatchdog", true}, // [e-26645:[258:org.apache.log4j.DailyRollingFileAppender -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23283:[238:org.apache.log4j.PropertyConfigurator -> 140:org.apache.log4j.helpers.FileWatchdog]]
                {"org.apache.log4j.helpers.PatternParser", "org.apache.log4j.helpers.PatternParser$BasicPatternConverter", true}, // [e-11997:[150:org.apache.log4j.helpers.PatternParser -> 142:org.apache.log4j.helpers.PatternParser$BasicPatternConverter]]
                {"org.apache.log4j.spi.RepositorySelector", "org.apache.log4j.helpers.LogLog", true}, // [e-9648:[122:org.apache.log4j.spi.RepositorySelector -> 112:org.apache.log4j.spi.LoggerRepository], e-9556:[112:org.apache.log4j.spi.LoggerRepository -> 129:org.apache.log4j.Category], e-10034:[129:org.apache.log4j.Category -> 220:org.apache.log4j.Hierarchy], e-21300:[220:org.apache.log4j.Hierarchy -> 139:org.apache.log4j.helpers.LogLog]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$24", "org.apache.log4j.lf5.util.DateFormatManager", true}, // [e-4038:[66:org.apache.log4j.lf5.viewer.LogBrokerMonitor$24 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5064:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 94:org.apache.log4j.lf5.util.DateFormatManager]]
                {"org.apache.log4j.chainsaw.ControlPanel$3", "org.apache.log4j.Appender", true}, // [e-14870:[178:org.apache.log4j.chainsaw.ControlPanel$3 -> 169:org.apache.log4j.chainsaw.MyTableModel], e-13921:[169:org.apache.log4j.chainsaw.MyTableModel -> 129:org.apache.log4j.Category], e-9859:[129:org.apache.log4j.Category -> 163:org.apache.log4j.Appender]]
                {"org.apache.log4j.spi.LoggingEvent", "org.apache.log4j.NDC", true}, // [e-9048:[108:org.apache.log4j.spi.LoggingEvent -> 247:org.apache.log4j.NDC]]
                {"org.apache.log4j.net.SMTPAppender$1", "org.apache.log4j.Hierarchy", true}, // [e-17465:[205:org.apache.log4j.net.SMTPAppender$1 -> 206:org.apache.log4j.net.SMTPAppender], e-17813:[206:org.apache.log4j.net.SMTPAppender -> 9:org.apache.log4j.xml.DOMConfigurator], e-576:[9:org.apache.log4j.xml.DOMConfigurator -> 240:org.apache.log4j.LogManager], e-24077:[240:org.apache.log4j.LogManager -> 220:org.apache.log4j.Hierarchy]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$22", "org.apache.log4j.lf5.LogLevelFormatException", true}, // [e-4016:[64:org.apache.log4j.lf5.viewer.LogBrokerMonitor$22 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5303:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 97:org.apache.log4j.lf5.util.LogFileParser], e-8340:[97:org.apache.log4j.lf5.util.LogFileParser -> 91:org.apache.log4j.lf5.LogLevelFormatException]]
                {"org.apache.log4j.jdbc.JDBCAppender", "org.apache.log4j.helpers.OnlyOnceErrorHandler", true}, // [e-25565:[252:org.apache.log4j.jdbc.JDBCAppender -> 166:org.apache.log4j.AppenderSkeleton], e-13428:[166:org.apache.log4j.AppenderSkeleton -> 134:org.apache.log4j.helpers.OnlyOnceErrorHandler]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$2", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1", true}, // [e-3643:[44:org.apache.log4j.lf5.viewer.LogBrokerMonitor$2 -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2069:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 15:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$2", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryAbstractCellEditor", true}, // [e-3643:[44:org.apache.log4j.lf5.viewer.LogBrokerMonitor$2 -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2103:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor], e-3043:[35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor -> 24:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryAbstractCellEditor]]
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryImmediateEditor", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNode", true}, // [e-2860:[26:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryImmediateEditor -> 19:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNode]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$19", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel$1", true}, // [e-3982:[61:org.apache.log4j.lf5.viewer.LogBrokerMonitor$19 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5353:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 18:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel], e-2289:[18:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel -> 17:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel$1]]
                {"org.apache.log4j.spi.AppenderAttachable", "org.apache.log4j.spi.LoggerRepository", true}, // [e-9271:[109:org.apache.log4j.spi.AppenderAttachable -> 163:org.apache.log4j.Appender], e-13293:[163:org.apache.log4j.Appender -> 108:org.apache.log4j.spi.LoggingEvent], e-9092:[108:org.apache.log4j.spi.LoggingEvent -> 112:org.apache.log4j.spi.LoggerRepository]]
                {"org.apache.log4j.lf5.LF5Appender", "org.apache.log4j.lf5.viewer.TrackingAdjustmentListener", true}, // [e-8633:[101:org.apache.log4j.lf5.LF5Appender -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-5219:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 84:org.apache.log4j.lf5.viewer.TrackingAdjustmentListener]]
                {"org.apache.log4j.helpers.FormattingInfo", "org.apache.log4j.or.ObjectRenderer", true}, // [e-12244:[151:org.apache.log4j.helpers.FormattingInfo -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23895:[238:org.apache.log4j.PropertyConfigurator -> 120:org.apache.log4j.spi.RendererSupport], e-9641:[120:org.apache.log4j.spi.RendererSupport -> 222:org.apache.log4j.or.ObjectRenderer]]
                {"org.apache.log4j.net.SocketHubAppender", "org.apache.log4j.spi.RepositorySelector", true}, // [e-16206:[199:org.apache.log4j.net.SocketHubAppender -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-9989:[129:org.apache.log4j.Category -> 240:org.apache.log4j.LogManager], e-23990:[240:org.apache.log4j.LogManager -> 122:org.apache.log4j.spi.RepositorySelector]]
                {"org.apache.log4j.net.SMTPAppender$1", "org.apache.log4j.spi.ErrorHandler", true}, // [e-17465:[205:org.apache.log4j.net.SMTPAppender$1 -> 206:org.apache.log4j.net.SMTPAppender], e-17628:[206:org.apache.log4j.net.SMTPAppender -> 117:org.apache.log4j.spi.ErrorHandler]]
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$8", true}, // [e-2036:[15:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1 -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2103:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor], e-3121:[35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor -> 34:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$8]]
                {"org.apache.log4j.WriterAppender", "org.apache.log4j.spi.NOPLogger", true}, // [e-21994:[228:org.apache.log4j.WriterAppender -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-9989:[129:org.apache.log4j.Category -> 240:org.apache.log4j.LogManager], e-24032:[240:org.apache.log4j.LogManager -> 125:org.apache.log4j.spi.NOPLoggerRepository], e-9738:[125:org.apache.log4j.spi.NOPLoggerRepository -> 124:org.apache.log4j.spi.NOPLogger]]
                {"org.apache.log4j.helpers.FileWatchdog", "org.apache.log4j.helpers.AppenderAttachableImpl", true}, // [e-11546:[140:org.apache.log4j.helpers.FileWatchdog -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23569:[238:org.apache.log4j.PropertyConfigurator -> 129:org.apache.log4j.Category], e-9847:[129:org.apache.log4j.Category -> 132:org.apache.log4j.helpers.AppenderAttachableImpl]]
                {"org.apache.log4j.helpers.FileWatchdog", "org.apache.log4j.helpers.OptionConverter", true}, // [e-11546:[140:org.apache.log4j.helpers.FileWatchdog -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter]]
                {"org.apache.log4j.chainsaw.ControlPanel$4", "org.apache.log4j.Layout", true}, // [e-14912:[179:org.apache.log4j.chainsaw.ControlPanel$4 -> 169:org.apache.log4j.chainsaw.MyTableModel], e-13921:[169:org.apache.log4j.chainsaw.MyTableModel -> 129:org.apache.log4j.Category], e-9859:[129:org.apache.log4j.Category -> 163:org.apache.log4j.Appender], e-13296:[163:org.apache.log4j.Appender -> 165:org.apache.log4j.Layout]]
                {"org.apache.log4j.spi.NOPLogger", "org.apache.log4j.Layout", true}, // [e-9663:[124:org.apache.log4j.spi.NOPLogger -> 163:org.apache.log4j.Appender], e-13296:[163:org.apache.log4j.Appender -> 165:org.apache.log4j.Layout]]
                {"org.apache.log4j.varia.StringMatchFilter", "org.apache.log4j.helpers.Loader", true}, // [e-15709:[189:org.apache.log4j.varia.StringMatchFilter -> 156:org.apache.log4j.helpers.OptionConverter], e-12445:[156:org.apache.log4j.helpers.OptionConverter -> 138:org.apache.log4j.helpers.Loader]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$31", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$9", true}, // [e-4209:[73:org.apache.log4j.lf5.viewer.LogBrokerMonitor$31 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4824:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 51:org.apache.log4j.lf5.viewer.LogBrokerMonitor$9]]
                {"org.apache.log4j.lf5.StartLogFactor5", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1", true}, // [e-8858:[105:org.apache.log4j.lf5.StartLogFactor5 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4269:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2069:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 15:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1]]
                {"org.apache.log4j.xml.DOMConfigurator$4", "org.apache.log4j.NDC", true}, // [e-440:[7:org.apache.log4j.xml.DOMConfigurator$4 -> 9:org.apache.log4j.xml.DOMConfigurator], e-1443:[9:org.apache.log4j.xml.DOMConfigurator -> 117:org.apache.log4j.spi.ErrorHandler], e-9599:[117:org.apache.log4j.spi.ErrorHandler -> 108:org.apache.log4j.spi.LoggingEvent], e-9048:[108:org.apache.log4j.spi.LoggingEvent -> 247:org.apache.log4j.NDC]]
                {"org.apache.log4j.helpers.PatternParser$DatePatternConverter", "org.apache.log4j.spi.LoggerRepository", true}, // [e-11700:[144:org.apache.log4j.helpers.PatternParser$DatePatternConverter -> 108:org.apache.log4j.spi.LoggingEvent], e-9092:[108:org.apache.log4j.spi.LoggingEvent -> 112:org.apache.log4j.spi.LoggerRepository]]
                {"org.apache.log4j.helpers.BoundedFIFO", "org.apache.log4j.CategoryKey", true}, // [e-10819:[133:org.apache.log4j.helpers.BoundedFIFO -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-10034:[129:org.apache.log4j.Category -> 220:org.apache.log4j.Hierarchy], e-21341:[220:org.apache.log4j.Hierarchy -> 251:org.apache.log4j.CategoryKey]]
                {"org.apache.log4j.chainsaw.ControlPanel$2", "org.apache.log4j.spi.OptionHandler", true}, // [e-14828:[177:org.apache.log4j.chainsaw.ControlPanel$2 -> 169:org.apache.log4j.chainsaw.MyTableModel], e-13921:[169:org.apache.log4j.chainsaw.MyTableModel -> 129:org.apache.log4j.Category], e-9859:[129:org.apache.log4j.Category -> 163:org.apache.log4j.Appender], e-13294:[163:org.apache.log4j.Appender -> 117:org.apache.log4j.spi.ErrorHandler], e-9593:[117:org.apache.log4j.spi.ErrorHandler -> 116:org.apache.log4j.spi.OptionHandler]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$24", "org.apache.log4j.lf5.PassingLogRecordFilter", true}, // [e-4038:[66:org.apache.log4j.lf5.viewer.LogBrokerMonitor$24 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4369:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 81:org.apache.log4j.lf5.viewer.FilteredLogTableModel], e-6999:[81:org.apache.log4j.lf5.viewer.FilteredLogTableModel -> 106:org.apache.log4j.lf5.PassingLogRecordFilter]]
                {"org.apache.log4j.net.JMSSink", "org.apache.log4j.spi.LocationInfo", true}, // [e-18442:[209:org.apache.log4j.net.JMSSink -> 108:org.apache.log4j.spi.LoggingEvent], e-8880:[108:org.apache.log4j.spi.LoggingEvent -> 111:org.apache.log4j.spi.LocationInfo]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$3", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$2", true}, // [e-3686:[45:org.apache.log4j.lf5.viewer.LogBrokerMonitor$3 -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2103:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor], e-3070:[35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor -> 28:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$2]]
                {"org.apache.log4j.helpers.LogLog", "org.apache.log4j.Layout", true}, // [e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23657:[238:org.apache.log4j.PropertyConfigurator -> 165:org.apache.log4j.Layout]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$18", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$28", true}, // [e-3971:[60:org.apache.log4j.lf5.viewer.LogBrokerMonitor$18 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4582:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 70:org.apache.log4j.lf5.viewer.LogBrokerMonitor$28]]
                {"org.apache.log4j.net.SocketHubAppender", "org.apache.log4j.config.PropertySetter", true}, // [e-16228:[199:org.apache.log4j.net.SocketHubAppender -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23325:[238:org.apache.log4j.PropertyConfigurator -> 230:org.apache.log4j.config.PropertySetter]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$6", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$23", true}, // [e-3747:[48:org.apache.log4j.lf5.viewer.LogBrokerMonitor$6 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4479:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 65:org.apache.log4j.lf5.viewer.LogBrokerMonitor$23]]
                {"org.apache.log4j.FileAppender", "org.apache.log4j.config.PropertySetterException", true}, // [e-26447:[257:org.apache.log4j.FileAppender -> 139:org.apache.log4j.helpers.LogLog], e-11469:[139:org.apache.log4j.helpers.LogLog -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23325:[238:org.apache.log4j.PropertyConfigurator -> 230:org.apache.log4j.config.PropertySetter], e-22371:[230:org.apache.log4j.config.PropertySetter -> 229:org.apache.log4j.config.PropertySetterException]]
                {"org.apache.log4j.chainsaw.ControlPanel$5", "org.apache.log4j.spi.AppenderAttachable", true}, // [e-14954:[180:org.apache.log4j.chainsaw.ControlPanel$5 -> 169:org.apache.log4j.chainsaw.MyTableModel], e-13921:[169:org.apache.log4j.chainsaw.MyTableModel -> 129:org.apache.log4j.Category], e-9845:[129:org.apache.log4j.Category -> 109:org.apache.log4j.spi.AppenderAttachable]]
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$7", true}, // [e-2103:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor], e-3095:[35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor -> 33:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$7]]
                {"org.apache.log4j.varia.StringMatchFilter", "org.apache.log4j.spi.HierarchyEventListener", true}, // [e-15683:[189:org.apache.log4j.varia.StringMatchFilter -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-10043:[129:org.apache.log4j.Category -> 113:org.apache.log4j.spi.HierarchyEventListener]]
                {"org.apache.log4j.chainsaw.DetailPanel", "org.apache.log4j.config.PropertySetter", true}, // [e-14242:[173:org.apache.log4j.chainsaw.DetailPanel -> 164:org.apache.log4j.Logger], e-13321:[164:org.apache.log4j.Logger -> 240:org.apache.log4j.LogManager], e-24083:[240:org.apache.log4j.LogManager -> 156:org.apache.log4j.helpers.OptionConverter], e-12621:[156:org.apache.log4j.helpers.OptionConverter -> 238:org.apache.log4j.PropertyConfigurator], e-23325:[238:org.apache.log4j.PropertyConfigurator -> 230:org.apache.log4j.config.PropertySetter]]
                {"org.apache.log4j.TTCCLayout", "org.apache.log4j.spi.RootLogger", true}, // [e-24169:[241:org.apache.log4j.TTCCLayout -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-9989:[129:org.apache.log4j.Category -> 240:org.apache.log4j.LogManager], e-24075:[240:org.apache.log4j.LogManager -> 119:org.apache.log4j.spi.RootLogger]]
                {"org.apache.log4j.DailyRollingFileAppender", "org.apache.log4j.or.ObjectRenderer", true}, // [e-26911:[258:org.apache.log4j.DailyRollingFileAppender -> 108:org.apache.log4j.spi.LoggingEvent], e-9096:[108:org.apache.log4j.spi.LoggingEvent -> 221:org.apache.log4j.or.RendererMap], e-21625:[221:org.apache.log4j.or.RendererMap -> 222:org.apache.log4j.or.ObjectRenderer]]
                {"org.apache.log4j.varia.StringMatchFilter", "org.apache.log4j.helpers.OptionConverter", true}, // [e-15709:[189:org.apache.log4j.varia.StringMatchFilter -> 156:org.apache.log4j.helpers.OptionConverter]]
                {"org.apache.log4j.lf5.util.LogFileParser", "org.apache.log4j.lf5.util.LogFileParser$1", true}, // [e-8391:[97:org.apache.log4j.lf5.util.LogFileParser -> 96:org.apache.log4j.lf5.util.LogFileParser$1]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$24", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$2", true}, // [e-4038:[66:org.apache.log4j.lf5.viewer.LogBrokerMonitor$24 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4269:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2103:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor], e-3070:[35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor -> 28:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$2]]
                {"org.apache.log4j.helpers.PatternParser", "org.apache.log4j.spi.ThrowableInformation", true}, // [e-11908:[150:org.apache.log4j.helpers.PatternParser -> 149:org.apache.log4j.helpers.PatternParser$CategoryPatternConverter], e-11796:[149:org.apache.log4j.helpers.PatternParser$CategoryPatternConverter -> 108:org.apache.log4j.spi.LoggingEvent], e-8888:[108:org.apache.log4j.spi.LoggingEvent -> 110:org.apache.log4j.spi.ThrowableInformation]]
                {"org.apache.log4j.chainsaw.ControlPanel$4", "org.apache.log4j.ProvisionNode", true}, // [e-14912:[179:org.apache.log4j.chainsaw.ControlPanel$4 -> 169:org.apache.log4j.chainsaw.MyTableModel], e-13921:[169:org.apache.log4j.chainsaw.MyTableModel -> 129:org.apache.log4j.Category], e-10034:[129:org.apache.log4j.Category -> 220:org.apache.log4j.Hierarchy], e-21433:[220:org.apache.log4j.Hierarchy -> 227:org.apache.log4j.ProvisionNode]]
                {"org.apache.log4j.or.ThreadGroupRenderer", "org.apache.log4j.LogManager", true}, // [e-21816:[224:org.apache.log4j.or.ThreadGroupRenderer -> 165:org.apache.log4j.Layout], e-13404:[165:org.apache.log4j.Layout -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-9989:[129:org.apache.log4j.Category -> 240:org.apache.log4j.LogManager]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$31", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNode", true}, // [e-4209:[73:org.apache.log4j.lf5.viewer.LogBrokerMonitor$31 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4269:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2049:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 19:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNode]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$21", "org.apache.log4j.lf5.viewer.LogTable$LogTableListSelectionListener", true}, // [e-4005:[63:org.apache.log4j.lf5.viewer.LogBrokerMonitor$21 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4288:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 78:org.apache.log4j.lf5.viewer.LogTable], e-5963:[78:org.apache.log4j.lf5.viewer.LogTable -> 77:org.apache.log4j.lf5.viewer.LogTable$LogTableListSelectionListener]]
                {"org.apache.log4j.AsyncAppender$DiscardSummary", "org.apache.log4j.Appender", true}, // [e-25804:[253:org.apache.log4j.AsyncAppender$DiscardSummary -> 129:org.apache.log4j.Category], e-9859:[129:org.apache.log4j.Category -> 163:org.apache.log4j.Appender]]
                {"org.apache.log4j.PatternLayout", "org.apache.log4j.Appender", true}, // [e-23946:[239:org.apache.log4j.PatternLayout -> 108:org.apache.log4j.spi.LoggingEvent], e-8881:[108:org.apache.log4j.spi.LoggingEvent -> 129:org.apache.log4j.Category], e-9859:[129:org.apache.log4j.Category -> 163:org.apache.log4j.Appender]]
                {"org.apache.log4j.PatternLayout", "org.apache.log4j.helpers.FormattingInfo", true}, // [e-23921:[239:org.apache.log4j.PatternLayout -> 141:org.apache.log4j.helpers.PatternConverter], e-11588:[141:org.apache.log4j.helpers.PatternConverter -> 151:org.apache.log4j.helpers.FormattingInfo]]
                {"org.apache.log4j.chainsaw.ControlPanel$1", "org.apache.log4j.Level", true}, // [e-14822:[176:org.apache.log4j.chainsaw.ControlPanel$1 -> 130:org.apache.log4j.Priority], e-10481:[130:org.apache.log4j.Priority -> 131:org.apache.log4j.Level]]
                {"org.apache.log4j.net.SimpleSocketServer", "org.apache.log4j.helpers.Loader", true}, // [e-17045:[202:org.apache.log4j.net.SimpleSocketServer -> 240:org.apache.log4j.LogManager], e-24097:[240:org.apache.log4j.LogManager -> 138:org.apache.log4j.helpers.Loader]]
                {"org.apache.log4j.jmx.Agent", "org.apache.log4j.spi.AppenderAttachable", true}, // [e-20656:[218:org.apache.log4j.jmx.Agent -> 129:org.apache.log4j.Category], e-9845:[129:org.apache.log4j.Category -> 109:org.apache.log4j.spi.AppenderAttachable]]
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$28", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor", true}, // [e-4119:[70:org.apache.log4j.lf5.viewer.LogBrokerMonitor$28 -> 76:org.apache.log4j.lf5.viewer.LogBrokerMonitor], e-4269:[76:org.apache.log4j.lf5.viewer.LogBrokerMonitor -> 16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree], e-2103:[16:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree -> 35:org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor]]
                {"org.apache.log4j.net.JMSAppender", "org.apache.log4j.NDC", true}, // [e-18132:[208:org.apache.log4j.net.JMSAppender -> 108:org.apache.log4j.spi.LoggingEvent], e-9048:[108:org.apache.log4j.spi.LoggingEvent -> 247:org.apache.log4j.NDC]]
                {"org.apache.log4j.helpers.PatternParser$BasicPatternConverter", "org.apache.log4j.NDC$DiagnosticContext", true}, // [e-11654:[142:org.apache.log4j.helpers.PatternParser$BasicPatternConverter -> 108:org.apache.log4j.spi.LoggingEvent], e-9048:[108:org.apache.log4j.spi.LoggingEvent -> 247:org.apache.log4j.NDC], e-25284:[247:org.apache.log4j.NDC -> 246:org.apache.log4j.NDC$DiagnosticContext]]
                // negative test case (not reachable)
                {"org.apache.log4j.varia.FallbackErrorHandler", "org.apache.log4j.TTCCLayout", false},
                {"org.apache.log4j.lf5.LogRecordFilter", "org.apache.log4j.net.DefaultEvaluator", false},
                {"org.apache.log4j.varia.StringMatchFilter", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$31", false},
                {"org.apache.log4j.net.JMSSink", "org.apache.log4j.lf5.viewer.LogTableRowRenderer", false},
                {"org.apache.log4j.xml.DOMConfigurator", "org.apache.log4j.lf5.LogRecordFilter", false},
                {"org.apache.log4j.varia.LevelRangeFilter", "org.apache.log4j.chainsaw.MyTableModel", false},
                {"org.apache.log4j.helpers.AbsoluteTimeDateFormat", "org.apache.log4j.or.ThreadGroupRenderer", false},
                {"org.apache.log4j.chainsaw.MyTableModel$1", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerLogRecordFilter", false},
                {"org.apache.log4j.spi.VectorWriter", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$29", false},
                {"org.apache.log4j.lf5.util.LogFileParser", "org.apache.log4j.or.ObjectRenderer", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$9", "org.apache.log4j.helpers.PatternParser$LocationPatternConverter", false},
                {"org.apache.log4j.helpers.PatternParser$CategoryPatternConverter", "org.apache.log4j.lf5.Log4JLogRecord", false},
                {"org.apache.log4j.Level", "org.apache.log4j.xml.DOMConfigurator$ParseAction", false},
                {"org.apache.log4j.xml.DOMConfigurator$5", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$25", false},
                {"org.apache.log4j.config.PropertySetter", "org.apache.log4j.lf5.viewer.LF5SwingUtils", false},
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1", "org.apache.log4j.net.SyslogAppender", false},
                {"org.apache.log4j.xml.DOMConfigurator$5", "org.apache.log4j.config.PropertyPrinter", false},
                {"org.apache.log4j.spi.RootCategory", "org.apache.log4j.chainsaw.ControlPanel$3", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$16", "org.apache.log4j.xml.Log4jEntityResolver", false},
                {"org.apache.log4j.helpers.DateTimeDateFormat", "org.apache.log4j.lf5.viewer.LogTableModel", false},
                {"org.apache.log4j.lf5.util.StreamUtils", "org.apache.log4j.spi.LoggerRepository", false},
                {"org.apache.log4j.chainsaw.XMLFileHandler", "org.apache.log4j.lf5.viewer.LogBrokerMonitor", false},
                {"org.apache.log4j.helpers.PatternParser$DatePatternConverter", "org.apache.log4j.jdbc.JDBCAppender", false},
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryAbstractCellEditor", "org.apache.log4j.varia.Roller", false},
                {"org.apache.log4j.helpers.PatternConverter", "org.apache.log4j.lf5.viewer.configure.MRUFileManager", false},
                {"org.apache.log4j.chainsaw.Main", "org.apache.log4j.lf5.viewer.LogFactor5ErrorDialog", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$6", "org.apache.log4j.chainsaw.Main", false},
                {"org.apache.log4j.helpers.PatternParser$LocationPatternConverter", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$18", false},
                {"org.apache.log4j.helpers.CountingQuietWriter", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$10", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$12", "org.apache.log4j.ConsoleAppender", false},
                {"org.apache.log4j.lf5.util.ResourceUtils", "org.apache.log4j.chainsaw.Main$1", false},
                {"org.apache.log4j.chainsaw.LoggingReceiver", "org.apache.log4j.lf5.viewer.LogBrokerMonitor", false},
                {"org.apache.log4j.lf5.viewer.LogTableColumnFormatException", "org.apache.log4j.HTMLLayout", false},
                {"org.apache.log4j.chainsaw.ControlPanel", "org.apache.log4j.AsyncAppender$Dispatcher", false},
                {"org.apache.log4j.lf5.LogLevel", "org.apache.log4j.xml.DOMConfigurator$5", false},
                {"org.apache.log4j.spi.NullWriter", "org.apache.log4j.helpers.CyclicBuffer", false},
                {"org.apache.log4j.ConsoleAppender", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryPath", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$21", "org.apache.log4j.varia.StringMatchFilter", false},
                {"org.apache.log4j.NDC$DiagnosticContext", "org.apache.log4j.chainsaw.DetailPanel", false},
                {"org.apache.log4j.spi.VectorWriter", "org.apache.log4j.varia.LevelMatchFilter", false},
                {"org.apache.log4j.varia.HUP", "org.apache.log4j.chainsaw.MyTableModel", false},
                {"org.apache.log4j.chainsaw.ControlPanel$1", "org.apache.log4j.varia.LevelMatchFilter", false},
                {"org.apache.log4j.config.PropertySetterException", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$8", false},
                {"org.apache.log4j.xml.DOMConfigurator$2", "org.apache.log4j.ConsoleAppender", false},
                {"org.apache.log4j.varia.ReloadingPropertyConfigurator", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$7", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$7", "org.apache.log4j.chainsaw.ExitAction", false},
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel", "org.apache.log4j.helpers.OnlyOnceErrorHandler", false},
                {"org.apache.log4j.varia.LevelRangeFilter", "org.apache.log4j.lf5.util.LogMonitorAdapter", false},
                {"org.apache.log4j.spi.ErrorCode", "org.apache.log4j.or.DefaultRenderer", false},
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$6", "org.apache.log4j.helpers.OnlyOnceErrorHandler", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$20", "org.apache.log4j.spi.VectorWriter", false},
                {"org.apache.log4j.or.ObjectRenderer", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$5", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$12", "org.apache.log4j.helpers.BoundedFIFO", false},
                {"org.apache.log4j.varia.LevelMatchFilter", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$8", false},
                {"org.apache.log4j.chainsaw.ControlPanel$1", "org.apache.log4j.lf5.viewer.configure.ConfigurationManager", false},
                {"org.apache.log4j.helpers.CountingQuietWriter", "org.apache.log4j.spi.ErrorCode", false},
                {"org.apache.log4j.xml.DOMConfigurator$5", "org.apache.log4j.helpers.FormattingInfo", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$20", "org.apache.log4j.helpers.SyslogQuietWriter", false},
                {"org.apache.log4j.chainsaw.MyTableModel$Processor", "org.apache.log4j.or.sax.AttributesRenderer", false},
                {"org.apache.log4j.xml.DOMConfigurator", "org.apache.log4j.lf5.LogRecord", false},
                {"org.apache.log4j.DailyRollingFileAppender", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$14", false},
                {"org.apache.log4j.Logger", "org.apache.log4j.FileAppender", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$13", "org.apache.log4j.xml.UnrecognizedElementHandler", false},
                {"org.apache.log4j.helpers.OptionConverter", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel$1", false},
                {"org.apache.log4j.helpers.AbsoluteTimeDateFormat", "org.apache.log4j.jmx.LayoutDynamicMBean", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$31", "org.apache.log4j.varia.NullAppender", false},
                {"org.apache.log4j.helpers.RelativeTimeDateFormat", "org.apache.log4j.helpers.CountingQuietWriter", false},
                {"org.apache.log4j.helpers.AbsoluteTimeDateFormat", "org.apache.log4j.xml.UnrecognizedElementHandler", false},
                {"org.apache.log4j.helpers.FormattingInfo", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$6", false},
                {"org.apache.log4j.lf5.util.DateFormatManager", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$27", false},
                {"org.apache.log4j.varia.LevelRangeFilter", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$4", false},
                {"org.apache.log4j.net.SMTPAppender", "org.apache.log4j.varia.NullAppender", false},
                {"org.apache.log4j.helpers.PatternParser$LiteralPatternConverter", "org.apache.log4j.net.TelnetAppender", false},
                {"org.apache.log4j.spi.RepositorySelector", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerModel", false},
                {"org.apache.log4j.lf5.viewer.LogFactor5ErrorDialog", "org.apache.log4j.net.SocketNode", false},
                {"org.apache.log4j.jmx.AppenderDynamicMBean", "org.apache.log4j.lf5.viewer.LogTableColumnFormatException", false},
                {"org.apache.log4j.Priority", "org.apache.log4j.lf5.LogLevel", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$16", "org.apache.log4j.WriterAppender", false},
                {"org.apache.log4j.net.TelnetAppender", "org.apache.log4j.xml.DOMConfigurator$ParseAction", false},
                {"org.apache.log4j.lf5.AppenderFinalizer", "org.apache.log4j.chainsaw.LoggingReceiver$Slurper", false},
                {"org.apache.log4j.DefaultCategoryFactory", "org.apache.log4j.varia.HUP", false},
                {"org.apache.log4j.net.TelnetAppender$SocketHandler", "org.apache.log4j.net.SocketHubAppender", false},
                {"org.apache.log4j.config.PropertySetterException", "org.apache.log4j.lf5.LogRecordFilter", false},
                {"org.apache.log4j.spi.AppenderAttachable", "org.apache.log4j.lf5.viewer.TrackingAdjustmentListener", false},
                {"org.apache.log4j.chainsaw.ControlPanel$6", "org.apache.log4j.Dispatcher", false},
                {"org.apache.log4j.or.RendererMap", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$30", false},
                {"org.apache.log4j.lf5.viewer.categoryexplorer.CategoryExplorerTree$1", "org.apache.log4j.DefaultCategoryFactory", false},
                {"org.apache.log4j.lf5.viewer.LogBrokerMonitor$24", "org.apache.log4j.helpers.FormattingInfo", false},
                {"org.apache.log4j.config.PropertyGetter$PropertyCallback", "org.apache.log4j.lf5.viewer.configure.ConfigurationManager", false},
                {"org.apache.log4j.xml.DOMConfigurator", "org.apache.log4j.lf5.viewer.categoryexplorer.CategoryNodeEditor$6", false},
                {"org.apache.log4j.Logger", "org.apache.log4j.helpers.PatternConverter", false},
                {"org.apache.log4j.TTCCLayout", "org.apache.log4j.lf5.viewer.LF5SwingUtils$1", false},
                {"org.apache.log4j.spi.RootLogger", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$31", false},
                {"org.apache.log4j.lf5.viewer.LogFactor5ErrorDialog$1", "org.apache.log4j.helpers.PatternParser", false},
                {"org.apache.log4j.xml.DOMConfigurator$1", "org.apache.log4j.chainsaw.EventDetails", false},
                {"org.apache.log4j.helpers.QuietWriter", "org.apache.log4j.lf5.viewer.LogBrokerMonitor$19", false},
                {"org.apache.log4j.spi.NullWriter", "org.apache.log4j.jmx.AbstractDynamicMBean", false},
                {"org.apache.log4j.varia.DenyAllFilter", "org.apache.log4j.lf5.LogRecordFilter", false},
                {"org.apache.log4j.xml.Log4jEntityResolver", "org.apache.log4j.helpers.FormattingInfo", false},
                {"org.apache.log4j.helpers.SyslogQuietWriter", "org.apache.log4j.chainsaw.ControlPanel", false}
        });
    }
}
