//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.23 at 02:18:43 PM NZST 
//


package nz.ac.massey.cs.guery.io.xml;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="annotate" type="{}annotate"/>
 *           &lt;element name="select" type="{}select"/>
 *           &lt;element name="constraint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="connectedBy" type="{}connectedBy"/>
 *           &lt;element name="notConnectedBy" type="{}notConnectedBy"/>
 *           &lt;element name="groupBy" type="{}groupBy"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "annotateOrSelectOrConstraint"
})
@XmlRootElement(name = "motif")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-23T02:18:43+12:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class Motif {

    @XmlElements({
            @XmlElement(name = "notConnectedBy", type = NotConnectedBy.class),
            @XmlElement(name = "groupBy", type = GroupBy.class),
            @XmlElement(name = "connectedBy", type = ConnectedBy.class),
            @XmlElement(name = "select", type = Select.class),
            @XmlElement(name = "constraint", type = String.class),
            @XmlElement(name = "annotate", type = Annotate.class)
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-23T02:18:43+12:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<Object> annotateOrSelectOrConstraint;
    @XmlAttribute
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-23T02:18:43+12:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String name;

    /**
     * Gets the value of the annotateOrSelectOrConstraint property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotateOrSelectOrConstraint property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotateOrSelectOrConstraint().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link NotConnectedBy }
     * {@link GroupBy }
     * {@link ConnectedBy }
     * {@link Select }
     * {@link String }
     * {@link Annotate }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-23T02:18:43+12:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<Object> getAnnotateOrSelectOrConstraint() {
        if (annotateOrSelectOrConstraint == null) {
            annotateOrSelectOrConstraint = new ArrayList<Object>();
        }
        return this.annotateOrSelectOrConstraint;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-23T02:18:43+12:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-23T02:18:43+12:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setName(String value) {
        this.name = value;
    }

}
